kasi_datainfra_data_modelling:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: kasi-production  # l GCP project ID
      dataset: kasi_datainfra_all_tables #  BigQuery dataset
      location: us-central1         #  region
      threads: 4                    # Number of threads to use for queries
