SELECT
    COALESCE(t.date, ut.date) AS date,
    t.sender_first_name,
    t.sender_last_name,
    t.sender_email,
    t.sender_user_name,
    COALESCE(t.sender_id, ut.sender_id) AS sender_id,
    t.sender_phone_number,
    COALESCE(
    SAFE_CAST(t.sender_amount.integer AS FLOAT64),
    SAFE_CAST(t.sender_amount.float AS FLOAT64),
    SAFE_CAST(t.sender_amount.string AS FLOAT64)
) AS sender_amount,

    t.sender_name,
    t.sender_reference,
    COALESCE(
        SAFE_CAST(t.fees.integer AS FLOAT64),
        t.fees.float
    ) AS fees,
    t.cash_advance_amount,
    COALESCE(SAFE_CAST(t.cash_advance_amount_owing.integer AS FLOAT64), t.cash_advance_amount_owing.float) AS cash_advance_amount_owing,
    COALESCE(SAFE_CAST(t.cash_advance_amount_paid.integer AS FLOAT64), t.cash_advance_amount_paid.float) AS cash_advance_amount_paid,
    COALESCE(SAFE_CAST(t.cash_advance_available_after.integer AS FLOAT64), t.cash_advance_available_after.float) AS cash_advance_available_after,
    COALESCE(SAFE_CAST(t.cash_advance_available_before.integer AS FLOAT64), t.cash_advance_available_before.float) AS cash_advance_available_before,
    t.cash_advance_fees,
    t.cash_advance_owed_after,
    COALESCE(t.cash_advance_fees_charged.float, SAFE_CAST(t.cash_advance_fees_charged.integer AS FLOAT64)) AS cash_advance_fees_charged,
    COALESCE(t.cash_advance_outstanding_amount.float, SAFE_CAST(t.cash_advance_outstanding_amount.integer AS FLOAT64)) AS cash_advance_outstanding_amount,
    COALESCE(t.cash_advance_owed_before.float, SAFE_CAST(t.cash_advance_owed_before.integer AS FLOAT64)) AS cash_advance_owed_before,
    COALESCE(t.cash_advance_total_owed.float, SAFE_CAST(t.cash_advance_total_owed.integer AS FLOAT64)) AS cash_advance_total_owed,
    t.cash_express_reference_id,
    t.cash_express_voucher_number,
    t.cash_express_voucher_status,
    t.voucher_code,
    t.refunded_by_id,
    t.refunded_by_name,
    t.refunded_by_phone_number,
    t.meter_number,
    t.reference,
    t.one_voucher_account_number,
    t.one_voucher_reference,
    t.one_voucher_serial_number,
    t.one_voucher_transaction_id,
    t.one_voucher_voucher_number,
    t.transaction_reference_id,
    t.receiver_account_number,
    COALESCE(SAFE_CAST(t.receiver_amount.integer AS FLOAT64), t.receiver_amount.float) AS receiver_amount,

    t.receiver_bank_id,
    t.receiver_bank_name,
    t.receiver_first_name,
    t.receiver_id,
     t.receiver_is_in_kasi,
    t.receiver_is_verified,
    t.receiver_last_name,
    t.receiver_name,
    t.receiver_phone_number,
    t.receiver_reference,
    t.receiver_user_name,
    t.electricity_voucher,


    COALESCE(t.merchant_id, ut.merchant_id) as merchant_id,
    t.franc_external_customer_id,
    t.franc_id,
    t.franc_reference,
    t.business_email,
    t.business_id,
    t.business_name,
    t.business_phone_number,
    COALESCE(t.state, ut.state) AS state,
    t.invoice_number,
     t.vault_id,
    used_credit,
    COALESCE(SAFE_CAST(t.debit.integer AS FLOAT64), t.debit.float, SAFE_CAST(ut.debit.integer AS FLOAT64), ut.debit.float) AS debit,
    COALESCE(SAFE_CAST(t.credit.integer AS FLOAT64), t.credit.float, SAFE_CAST(ut.credit AS FLOAT64)) AS credit,
    COALESCE(t.transaction_id, ut.transaction_id) AS transaction_id,
    COALESCE(t.transaction_type, ut.transaction_type) AS transaction_type,
    t.transaction_seen,
    t.goal_identifier,
    COALESCE(t.date_settled, ut.date_settled) AS date_settled,
    t.deposited_by,
    t.deposited_by_id,
    t.payment_reference,
    t.savings_id,
    t.savings_name,
    t.franc_transaction_id,
    t.transaction_redeemed,
    COALESCE(CAST(t.running_account_balance_before_payment.integer AS FLOAT64), t.running_account_balance_before_payment.float ) as running_account_balance_before_payment,
    COALESCE(CAST(t.running_account_balance_after_payment.integer AS FLOAT64), t.running_account_balance_after_payment.float) as running_account_balance_after_payment

 FROM    `kasi-production.kasi_datainfra_firestore_export_from_gcs.transactions` AS t
FULL OUTER JOIN
    `kasi-production.kasi_datainfra_firestore_export_from_gcs.uncleared_transactions` AS ut
ON
    t.transaction_id = ut.transaction_id
