version: 2

models:
  - name: onboarding_account_creation
    description: "This model extracts event data from the Mixpanel source, with conditional extraction for profession and other event properties."
    columns:
      - name: user_id
        description: "The unique identifier for the user."
        tests:
          - unique

      - name: time
        description: "The timestamp when the event occurred."
        tests:
          - not_null

      - name: event_name
        description: "The name of the event (e.g., create_customer_complete, customer_profession, $ae_first_open)."
        tests:
          - not_null

      - name: profession
        description: "The profession extracted for customer_profession events. NULL for other events."
        tests:
          - relationships:
              to: ref('your_reference_table')  # If profession relates to another table, add this relationship

      - name: mp_country_code
        description: "The country code of the user, extracted from the event properties."

      - name: region
        description: "The region where the user is located, extracted from the event properties."

      - name: city
        description: "The city where the user is located, extracted from the event properties."

      - name: app_version
        description: "The app version used during the event."

      - name: device_id
        description: "The unique device identifier used in the event."

      - name: brand
        description: "The brand of the user's device."

      - name: carrier
        description: "The carrier service used by the user."

      - name: has_telephone
        description: "Whether the user has a telephone feature."

      - name: manufacturer
        description: "The manufacturer of the user's device."

      - name: model
        description: "The model of the user's device."

      - name: os
        description: "The operating system of the user's device."

      - name: os_version
        description: "The version of the operating system used."


sources:
  - name: mixpanel_existing_data
    description: "Raw Mixpanel event data"
    tables:
      - name: mp_master_event
        description: "Events data from Mixpanel"
